import type { Author, Blog, Category, Tag, Comment, Review, Testimonial, TeamMember } from '@/src/types';

export const authors: Author[] = [
  { id: '1', name: 'Dr. Sarah Chen', avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150', bio: 'AI researcher and technology writer with 10+ years of experience.', role: 'Senior AI Researcher' },
  { id: '2', name: 'Marcus Williams', avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150', bio: 'Former Google Brain engineer turned technology journalist.', role: 'Lead Technical Writer' },
  { id: '3', name: 'Priya Sharma', avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150', bio: 'Computer vision expert and AI ethicist.', role: 'Computer Vision Expert' },
  { id: '4', name: 'James Rodriguez', avatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150', bio: 'Robotics engineer and AI safety researcher.', role: 'Robotics Specialist' },
];

export const categories: Category[] = [
  { id: '1', name: 'AI Agents', slug: 'ai-agents', color: '#0ea5e9', count: 48 },
  { id: '2', name: 'LLMs', slug: 'llms', color: '#10b981', count: 65 },
  { id: '3', name: 'Generative AI', slug: 'generative-ai', color: '#f59e0b', count: 72 },
  { id: '4', name: 'Robotics', slug: 'robotics', color: '#ef4444', count: 34 },
  { id: '5', name: 'Machine Learning', slug: 'machine-learning', color: '#8b5cf6', count: 89 },
  { id: '6', name: 'Computer Vision', slug: 'computer-vision', color: '#ec4899', count: 41 },
];

export const tags: Tag[] = [
  { id: '1', name: 'GPT-4', slug: 'gpt-4' },
  { id: '2', name: 'Claude', slug: 'claude' },
  { id: '3', name: 'Gemini', slug: 'gemini' },
  { id: '4', name: 'Llama', slug: 'llama' },
  { id: '5', name: 'Stable Diffusion', slug: 'stable-diffusion' },
  { id: '6', name: 'DALL-E', slug: 'dall-e' },
  { id: '7', name: 'Transformer', slug: 'transformer' },
  { id: '8', name: 'Neural Networks', slug: 'neural-networks' },
];

const blogContent = `
<h2>Introduction</h2>
<p>Artificial intelligence is transforming industries at an unprecedented pace. From healthcare to finance, AI systems are now capable of performing complex tasks that once required human expertise.</p>

<h2>The Rise of Foundation Models</h2>
<p>Foundation models represent a paradigm shift in how we build AI systems. Unlike traditional models trained for specific tasks, foundation models are trained on vast amounts of data and can be adapted to a wide range of applications.</p>

<blockquote><p>"We are at an inflection point in AI development. The models we are building today will fundamentally change how humans interact with technology."</p></blockquote>

<h3>Key Characteristics</h3>
<ul><li>Trained on diverse, large-scale datasets</li><li>Capable of few-shot and zero-shot learning</li><li>Adaptable to downstream tasks through fine-tuning</li></ul>

<h2>Challenges and Ethical Considerations</h2>
<p>As AI systems become more capable, we must address critical challenges including bias, fairness, transparency, and the societal impact of automation.</p>

<h2>Looking Ahead</h2>
<p>The next decade promises even more dramatic advances in AI capabilities. Multimodal models, AI agents, and neuromorphic computing are just a few areas where we can expect breakthrough developments.</p>
`;

export const blogs: Blog[] = [
  { id: '1', slug: 'gpt-4-vs-claude-3', title: 'GPT-4 vs Claude 3: A Comprehensive Comparison', excerpt: 'An in-depth analysis of the two most powerful language models available today.', content: blogContent, thumbnail: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=800', featuredImage: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=1200', category: categories[1], tags: [tags[0], tags[1]], author: authors[1], publishedAt: '2025-05-15T10:00:00Z', readTime: 12, views: 45820, likes: 1240, bookmarks: 342, featured: true, trending: true, rating: 4.8, reviewCount: 156 },
  { id: '2', slug: 'ai-agents-future', title: 'The Future of AI Agents: How Autonomous Systems Are Reshaping Industries', excerpt: 'AI agents are moving beyond chatbots to become autonomous systems capable of complex reasoning.', content: blogContent, thumbnail: 'https://images.pexels.com/photos/8386434/pexels-photo-8386434.jpeg?auto=compress&cs=tinysrgb&w=800', featuredImage: 'https://images.pexels.com/photos/8386434/pexels-photo-8386434.jpeg?auto=compress&cs=tinysrgb&w=1200', category: categories[0], tags: [tags[6]], author: authors[0], publishedAt: '2025-05-12T08:30:00Z', readTime: 9, views: 38400, likes: 980, bookmarks: 215, featured: true, trending: true, rating: 4.7, reviewCount: 98 },
  { id: '3', slug: 'stable-diffusion-3', title: 'Stable Diffusion 3: How This Model Revolutionizes Image Generation', excerpt: "Stability AI's latest model brings unprecedented photorealism to AI image generation.", content: blogContent, thumbnail: 'https://images.pexels.com/photos/3861958/pexels-photo-3861958.jpeg?auto=compress&cs=tinysrgb&w=800', featuredImage: 'https://images.pexels.com/photos/3861958/pexels-photo-3861958.jpeg?auto=compress&cs=tinysrgb&w=1200', category: categories[2], tags: [tags[4], tags[5]], author: authors[2], publishedAt: '2025-05-10T14:00:00Z', readTime: 7, views: 32100, likes: 876, bookmarks: 198, featured: false, trending: true, rating: 4.5, reviewCount: 87 },
  { id: '4', slug: 'boston-dynamics-atlas', title: 'Boston Dynamics Atlas: The Next Generation of Humanoid Robots', excerpt: 'The latest Atlas robot showcases unprecedented dexterity and cognitive capabilities.', content: blogContent, thumbnail: 'https://images.pexels.com/photos/8566473/pexels-photo-8566473.jpeg?auto=compress&cs=tinysrgb&w=800', featuredImage: 'https://images.pexels.com/photos/8566473/pexels-photo-8566473.jpeg?auto=compress&cs=tinysrgb&w=1200', category: categories[3], tags: [], author: authors[3], publishedAt: '2025-05-08T09:00:00Z', readTime: 10, views: 28900, likes: 742, bookmarks: 163, featured: false, trending: false, rating: 4.6, reviewCount: 72 },
  { id: '5', slug: 'transfer-learning-breakthrough', title: 'Transfer Learning Breakthrough: Training AI with Minimal Data', excerpt: 'New techniques in transfer learning are making it possible to train high-performance models with a fraction of the traditionally required data.', content: blogContent, thumbnail: 'https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&cs=tinysrgb&w=800', featuredImage: 'https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&cs=tinysrgb&w=1200', category: categories[4], tags: [tags[7]], author: authors[0], publishedAt: '2025-05-06T11:00:00Z', readTime: 8, views: 22400, likes: 654, bookmarks: 187, featured: false, trending: false, rating: 4.4, reviewCount: 63 },
  { id: '6', slug: 'vision-transformers-medical', title: 'Vision Transformers in Medical Imaging: A Revolution in Diagnostics', excerpt: 'How ViTs are achieving superhuman accuracy in medical image analysis.', content: blogContent, thumbnail: 'https://images.pexels.com/photos/3825586/pexels-photo-3825586.jpeg?auto=compress&cs=tinysrgb&w=800', featuredImage: 'https://images.pexels.com/photos/3825586/pexels-photo-3825586.jpeg?auto=compress&cs=tinysrgb&w=1200', category: categories[5], tags: [tags[6], tags[7]], author: authors[2], publishedAt: '2025-05-04T13:00:00Z', readTime: 11, views: 19800, likes: 521, bookmarks: 142, featured: false, trending: false, rating: 4.7, reviewCount: 55 },
  { id: '7', slug: 'llama-3-open-source', title: 'Llama 3 and the Open Source AI Revolution', excerpt: "Meta's Llama 3 signals a major shift in democratizing access to state-of-the-art language models.", content: blogContent, thumbnail: 'https://images.pexels.com/photos/7567443/pexels-photo-7567443.jpeg?auto=compress&cs=tinysrgb&w=800', featuredImage: 'https://images.pexels.com/photos/7567443/pexels-photo-7567443.jpeg?auto=compress&cs=tinysrgb&w=1200', category: categories[1], tags: [tags[3]], author: authors[1], publishedAt: '2025-05-02T09:30:00Z', readTime: 8, views: 41200, likes: 1089, bookmarks: 298, featured: false, trending: true, rating: 4.9, reviewCount: 124 },
  { id: '8', slug: 'google-gemini-ultra', title: 'Google Gemini Ultra: Redefining Multimodal AI Capabilities', excerpt: "Google's flagship model demonstrates remarkable reasoning across text, images, audio, and video.", content: blogContent, thumbnail: 'https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=800', featuredImage: 'https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=1200', category: categories[1], tags: [tags[2]], author: authors[1], publishedAt: '2025-04-28T14:30:00Z', readTime: 9, views: 35700, likes: 912, bookmarks: 256, featured: true, trending: true, rating: 4.8, reviewCount: 108 },
  { id: '9', slug: 'reinforcement-learning-robotics', title: 'Reinforcement Learning in Robotics: Teaching Machines to Learn', excerpt: 'How RL algorithms are enabling robots to master complex physical tasks through trial and error.', content: blogContent, thumbnail: 'https://images.pexels.com/photos/2599244/pexels-photo-2599244.jpeg?auto=compress&cs=tinysrgb&w=800', featuredImage: 'https://images.pexels.com/photos/2599244/pexels-photo-2599244.jpeg?auto=compress&cs=tinysrgb&w=1200', category: categories[3], tags: [tags[7]], author: authors[3], publishedAt: '2025-04-25T10:00:00Z', readTime: 10, views: 18500, likes: 478, bookmarks: 134, featured: false, trending: false, rating: 4.6, reviewCount: 48 },
  { id: '10', slug: 'prompt-engineering-guide', title: 'The Ultimate Guide to Prompt Engineering for LLMs', excerpt: 'Master the art of crafting effective prompts to get the best results from language models.', content: blogContent, thumbnail: 'https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg?auto=compress&cs=tinysrgb&w=800', featuredImage: 'https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg?auto=compress&cs=tinysrgb&w=1200', category: categories[1], tags: [tags[0], tags[1], tags[2]], author: authors[0], publishedAt: '2025-04-22T08:00:00Z', readTime: 15, views: 52300, likes: 1456, bookmarks: 412, featured: false, trending: true, rating: 4.9, reviewCount: 189 },
  { id: '11', slug: 'ai-code-generation', title: 'AI-Powered Code Generation: The Future of Software Development', excerpt: 'How AI coding assistants are transforming the way developers write and review code.', content: blogContent, thumbnail: 'https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&w=800', featuredImage: 'https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&w=1200', category: categories[0], tags: [tags[0], tags[1]], author: authors[1], publishedAt: '2025-04-18T11:30:00Z', readTime: 9, views: 29800, likes: 823, bookmarks: 245, featured: false, trending: false, rating: 4.7, reviewCount: 92 },
  { id: '12', slug: 'neural-network-architectures', title: 'Deep Dive into Modern Neural Network Architectures', excerpt: 'Exploring the evolution from CNNs and RNNs to Transformers and beyond.', content: blogContent, thumbnail: 'https://images.pexels.com/photos/1089438/pexels-photo-1089438.jpeg?auto=compress&cs=tinysrgb&w=800', featuredImage: 'https://images.pexels.com/photos/1089438/pexels-photo-1089438.jpeg?auto=compress&cs=tinysrgb&w=1200', category: categories[4], tags: [tags[6], tags[7]], author: authors[2], publishedAt: '2025-04-15T14:00:00Z', readTime: 13, views: 24200, likes: 687, bookmarks: 198, featured: false, trending: false, rating: 4.8, reviewCount: 76 },
  { id: '13', slug: 'generative-video-ai', title: 'Generative Video AI: Creating Cinematic Content with AI', excerpt: 'How AI models like Sora and Runway are revolutionizing video production.', content: blogContent, thumbnail: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=800', featuredImage: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=1200', category: categories[2], tags: [tags[4], tags[5]], author: authors[0], publishedAt: '2025-04-12T09:00:00Z', readTime: 8, views: 31500, likes: 892, bookmarks: 267, featured: false, trending: true, rating: 4.6, reviewCount: 84 },
  { id: '14', slug: 'ai-ethics-fairness', title: 'AI Ethics and Fairness: Building Responsible AI Systems', excerpt: 'Addressing bias, transparency, and accountability in AI development and deployment.', content: blogContent, thumbnail: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?auto=compress&cs=tinysrgb&w=800', featuredImage: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?auto=compress&cs=tinysrgb&w=1200', category: categories[4], tags: [], author: authors[2], publishedAt: '2025-04-08T13:30:00Z', readTime: 11, views: 17600, likes: 512, bookmarks: 156, featured: false, trending: false, rating: 4.5, reviewCount: 62 },
  { id: '15', slug: 'edge-ai-iot', title: 'Edge AI: Running Machine Learning on IoT Devices', excerpt: 'How edge computing is bringing AI processing closer to where data is generated.', content: blogContent, thumbnail: 'https://images.pexels.com/photos/163097/pexels-photo-163097.jpeg?auto=compress&cs=tinysrgb&w=800', featuredImage: 'https://images.pexels.com/photos/163097/pexels-photo-163097.jpeg?auto=compress&cs=tinysrgb&w=1200', category: categories[5], tags: [tags[7]], author: authors[3], publishedAt: '2025-04-05T10:00:00Z', readTime: 9, views: 21300, likes: 598, bookmarks: 178, featured: false, trending: false, rating: 4.6, reviewCount: 58 },
  { id: '16', slug: 'multimodal-learning', title: 'Multimodal Learning: Teaching AI to Understand the World', excerpt: 'How models that process text, images, and audio together are pushing AI boundaries.', content: blogContent, thumbnail: 'https://images.pexels.com/photos/2004161/pexels-photo-2004161.jpeg?auto=compress&cs=tinysrgb&w=800', featuredImage: 'https://images.pexels.com/photos/2004161/pexels-photo-2004161.jpeg?auto=compress&cs=tinysrgb&w=1200', category: categories[4], tags: [tags[6]], author: authors[1], publishedAt: '2025-04-01T08:30:00Z', readTime: 12, views: 26800, likes: 756, bookmarks: 223, featured: false, trending: false, rating: 4.7, reviewCount: 71 },
  { id: '17', slug: 'autonomous-vehicles-perception', title: 'Autonomous Vehicle Perception Systems Explained', excerpt: 'A technical deep dive into how self-driving cars see and understand their environment.', content: blogContent, thumbnail: 'https://images.pexels.com/photos/120049/pexels-photo-120049.jpeg?auto=compress&cs=tinysrgb&w=800', featuredImage: 'https://images.pexels.com/photos/120049/pexels-photo-120049.jpeg?auto=compress&cs=tinysrgb&w=1200', category: categories[3], tags: [tags[6], tags[7]], author: authors[3], publishedAt: '2025-03-28T11:00:00Z', readTime: 14, views: 32400, likes: 912, bookmarks: 289, featured: false, trending: false, rating: 4.8, reviewCount: 95 },
  { id: '18', slug: 'rag-systems', title: 'Retrieval-Augmented Generation: Building Smarter AI Systems', excerpt: 'How RAG combines the power of LLMs with external knowledge bases for better accuracy.', content: blogContent, thumbnail: 'https://images.pexels.com/photos/4164418/pexels-photo-4164418.jpeg?auto=compress&cs=tinysrgb&w=800', featuredImage: 'https://images.pexels.com/photos/4164418/pexels-photo-4164418.jpeg?auto=compress&cs=tinysrgb&w=1200', category: categories[1], tags: [tags[0], tags[1]], author: authors[0], publishedAt: '2025-03-24T14:30:00Z', readTime: 10, views: 38700, likes: 1045, bookmarks: 312, featured: false, trending: true, rating: 4.9, reviewCount: 132 },
];

export const comments: Comment[] = [
  { id: '1', blogId: '1', parentId: null, author: { name: 'Alex Thompson', avatar: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=100' }, content: 'Excellent comparison! The section on reasoning capabilities was particularly insightful.', likes: 24, createdAt: '2025-05-16T08:30:00Z', replies: [
    { id: '2', blogId: '1', parentId: '1', author: { name: 'Emma Davis', avatar: 'https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=100' }, content: 'Agreed! Claude tends to produce more idiomatic code in my testing.', likes: 12, createdAt: '2025-05-16T09:15:00Z', replies: [] },
  ] },
  { id: '3', blogId: '1', parentId: null, author: { name: 'Jennifer Liu', avatar: 'https://images.pexels.com/photos/1065084/pexels-photo-1065084.jpeg?auto=compress&cs=tinysrgb&w=100' }, content: 'Great article! Would love to see a follow-up on multimodal capabilities.', likes: 18, createdAt: '2025-05-17T11:00:00Z', replies: [] },
];

export const reviews: Review[] = [
  { id: '1', blogId: '1', author: { name: 'Michael Chang', email: 'michael@example.com', avatar: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=100' }, rating: 5, content: 'Incredibly thorough and well-researched. The benchmark breakdowns are especially useful.', createdAt: '2025-05-16T14:00:00Z', helpful: 45 },
  { id: '2', blogId: '1', author: { name: 'Sophie Martin', email: 'sophie@example.com', avatar: 'https://images.pexels.com/photos/1036622/pexels-photo-1036622.jpeg?auto=compress&cs=tinysrgb&w=100' }, rating: 4, content: 'Very informative. Only giving 4 stars because I wish it covered more about safety features.', createdAt: '2025-05-17T09:30:00Z', helpful: 28 },
];

export const testimonials: Testimonial[] = [
  { id: '1', author: 'Sarah Mitchell', role: 'CTO', company: 'TechVentures Inc.', avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=100', content: 'AI Insights Hub is my go-to source for staying updated on AI developments. The depth of analysis and quality of writing is unmatched.', rating: 5 },
  { id: '2', author: 'James Chen', role: 'ML Engineer', company: 'DeepMind', avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=100', content: 'I recommend this platform to every engineer on my team. The technical accuracy and breadth of coverage is exceptional.', rating: 5 },
  { id: '3', author: 'Aisha Johnson', role: 'AI Product Manager', company: 'Stripe', avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=100', content: 'From beginner-friendly introductions to deep technical dives, AI Insights Hub covers the entire spectrum brilliantly.', rating: 5 },
];

export const teamMembers: TeamMember[] = [
  { id: '1', name: 'Dr. Sarah Chen', role: 'Chief Editor & AI Researcher', avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=300', bio: 'Former Google AI researcher with 15 years of experience in machine learning.' },
  { id: '2', name: 'Marcus Williams', role: 'Technical Director', avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=300', bio: 'Ex-Google Brain engineer and technology journalist covering AI for over a decade.' },
  { id: '3', name: 'Priya Sharma', role: 'Head of Research', avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=300', bio: 'PhD from MIT AI Lab, specializing in computer vision and AI ethics.' },
  { id: '4', name: 'James Rodriguez', role: 'Senior Writer', avatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=300', bio: 'Robotics engineer and AI safety researcher covering autonomous systems.' },
];
